services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./db.env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 5s
        timeout: 3s
        retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app
      - ./backend/app/media:/app/media
      - static_volume:/app/static       

    ports:
      - "8002:8002"
    depends_on:
       db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "8181:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  proxy:
    build: ./nginx
    # Пробрасываем 80 наружу (Nginx будет слушать на 80)
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    # Если нужно, монтируем volume c медиа-файлами Django:
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./frontend/build:/usr/share/nginx/html:ro
      - static_volume:/static:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot:/etc/letsencrypt  # общий volume под серты
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - proxy

volumes:
  postgres_data:
  static_volume:
