services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: kb971033
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app
      - ./backend/app/media:/app/media

    ports:
      - "8002:8002"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8181:5173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
      - ./frontend/svelte.config.js:/app/svelte.config.js
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json

  proxy:
    build: ./nginx
    # Пробрасываем 80 наружу (Nginx будет слушать на 80)
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    # Если нужно, монтируем volume c медиа-файлами Django:
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro

volumes:
  postgres_data: