# Generated by Django 5.1.3 on 2025-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_attribute_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='advantages',
            field=models.TextField(blank=True, null=True, verbose_name='Advantages (one per line)'),
        ),
        migrations.DeleteModel(
            name='ProductAdvantage',
        ),
    ]
