# Generated by Django 5.1.3 on 2025-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productinfo_advantages_delete_productadvantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Photo'),
        ),
    ]
