server {
    listen 80;
    server_name mustang-farbe.kz www.mustang-farbe.kz;

    # Разрешаем Let's Encrypt читать challenge-файлы,
    # чтобы Certbot мог выпускать и продлевать сертификаты
    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    # Все остальные запросы редиректим на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
	listen 443 ssl;
	server_name mustang-farbe.kz www.mustang-farbe.kz;

	ssl_certificate /etc/letsencrypt/live/mustang-farbe.kz/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/mustang-farbe.kz/privkey.pem;

    # API запросы на бэкенд
    location /api/ {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass http://backend:8002/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /admin/ {
            proxy_pass http://backend:8002/admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
        	proxy_set_header X-Forwarded-Proto $scheme;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }


    # Проксирование медиафайлов напрямую с бэкенда
    location /media/ {
        proxy_pass http://backend:8002/media/;
    }

	 location /static/ {
	      alias /static/;   # путь внутри контейнера nginx → volume static_volume
	      access_log off;
	      expires 30d;
	}

    # Статика фронтенда
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
