# Generated by Django 5.1.3 on 2025-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointsSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Points Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_points', models.BooleanField(default=True, verbose_name='Is Our Points')),
            ],
            options={
                'verbose_name': 'Points Name',
                'verbose_name_plural': 'Points Name',
            },
        ),
    ]
