# Generated by Django 5.1.3 on 2025-03-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointssales',
            name='address',
            field=models.CharField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
