# Generated by Django 5.1.3 on 2025-03-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_storeinfo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='phone',
            field=models.TextField(blank=True, default=1, max_length=50, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
