# Generated by Django 5.1.3 on 2025-03-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_storeinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointssales',
            name='city',
            field=models.CharField(blank=True, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='pointssales',
            name='country',
            field=models.CharField(blank=True, null=True, verbose_name='Country'),
        ),
    ]
